# Copyright (c) 2025 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/templates/build_template.gni")
import("//build/toolchain/blueos.gni")

build_rust("blueos_driver") {
  sources = [ "src/lib.rs" ]
  deps = [
           "//external/vendor/bitflags-2.10.0:bitflags",
           "//external/vendor/cfg-if-1.0.4:cfg_if",
           "//external/vendor/safe-mmio-0.2.5:safe_mmio",
           "//external/vendor/spin-0.9.8:spin",
           "//external/vendor/tock-registers-0.9.0:tock_registers",
           "//external/vendor/zerocopy-0.8.27:zerocopy",
           "//external/vendor/log-0.4.28:log",
           "//kernel/hal:blueos_hal",
           "//kernel/kconfig:generate_rustflags_file",
         ] + board_deps
  proc_macro_deps = [ "//kernel/macro:blueos_macro" ]

  features = []
  rustflags = [
    "--cfg",
    "target_board=\"${board}\"",
  ]

  configs += [ "//kernel/kconfig:kconfigs" ]
}
